# Generated by Django 4.2.4 on 2023-09-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy',
        ),
    ]
