# Generated by Django 4.2.4 on 2023-09-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
