# Generated by Django 4.2.4 on 2023-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_buy_price_buy_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='quantity',
        ),
        migrations.AddField(
            model_name='buy',
            name='modep',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
