# Generated by Django 4.2.4 on 2023-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_remove_buy_quantity_buy_modep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='modep',
        ),
        migrations.AddField(
            model_name='buy',
            name='option1',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='option2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='option3',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
