# Generated by Django 4.2.4 on 2023-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_remove_buy_modep_buy_option1_buy_option2_buy_option3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='option3',
        ),
        migrations.AddField(
            model_name='buy',
            name='mode',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
